runtime: python39 # or another supported version

#instance_class: F2
#
#env_variables:
#  BUCKET_NAME: "example-gcs-bucket"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  line_bot_api: "7d1g9wCrKfTEoxYDJ/xBDz1431u5ghkL7jz9Xma3jbvQXyJ6DhYegZc4+xTqVZ66RxWdmcxWVouqk+i35L1XapgE1b0V5oRwiiRFrZSKPHYzYDIjT7cHg0tCcdMtXmSJvjcaNwEFVt3D/D4w+MFxMAdB04t89/1O/w1cDnyilFU="
  CHANNEL_SECRET: "a9d95660b8fa434c63c8997e2135c41b"


#entrypoint: "gunicorn --bind:$PORT main:app"

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 7


#runtime: python39 # or another supported version
#instance_class: F2
#
#env_variables:
#  BUCKET_NAME: "example-gcs-bucket"
#
#handlers:
## Matches requests to /images/... to files in static/images/...
#- url: /images
#  static_dir: static/images
#
#- url: /.*
#  secure: always
#  redirect_http_response_code: 301
#  script: auto
#
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 7
#
#entrypoint: gunicorn -b :8080 -w 2 main:app
